//
//  GalleryProtocols.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 27/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation
import UPAXNetworking
import ZeusCoreDesignSystem

//MARK: Presenter -> Router
protocol GalleryWireframeProtocol: AnyObject {
    func showAlert()
    func showPreview(photo:Photo)
}

//MARK: View -> Presenter
protocol GalleryPresenterProtocol: AnyObject {
    var interactor: GalleryInteractorInputProtocol? { get set }
    var results:[Photo]{get set}
    var currentPage:Int{get}
    var totalPages:Int{get set}
    func requestPrevious()
    func requestNext()
    func search(word:String)
    func onClick(index:Int)
}

//MARK: Interactor -> Presenter
protocol GalleryInteractorOutputProtocol: AnyObject {
    
    func set(response:BaseResponse)
    func error(mesage:String)
}

//MARK: Presenter -> Interactor
protocol GalleryInteractorInputProtocol: AnyObject {
    var presenter: GalleryInteractorOutputProtocol?  { get set }
    var page:Int {get set}
    var word:String {get set}
    var networking:Networking { get set }
    func requestPrevious()
    func requestNext()
    func search(word:String)
}

//MARK: Presenter -> View
protocol GalleryViewProtocol: AnyObject {
    var presenter: GalleryPresenterProtocol?  { get set }
    func reloadPaginator()
    func reloadData()
    
}
