//
//  GalleryRouter.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 27/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

public class GalleryRouter: GalleryWireframeProtocol {
   
    
    weak var viewController: UIViewController?

    public static func createModule() -> UIViewController {
        let view = GalleryViewController()
        let interactor = GalleryInteractor()
        let router = GalleryRouter()
        let presenter = GalleryPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showAlert() {
        
    }
    
    func showPreview(photo:Photo) {
        let vc=DetailsRouter.createModule(photo: photo)
        vc.modalPresentationStyle = .overFullScreen
        self.viewController?.present(vc, animated: true)
    }
}
