//
//  DetailsPresenter.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 28/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class DetailsPresenter {
    weak private var view: DetailsViewProtocol?
    var interactor: DetailsInteractorInputProtocol?
    private let router: DetailsWireframeProtocol
    var photo: Photo?

    init(interface: DetailsViewProtocol, interactor: DetailsInteractorInputProtocol?, router: DetailsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension DetailsPresenter: DetailsPresenterProtocol {
    func openGallery() {
        router.openGallery()
    }
    
    func downloadAndSaveImage(from urlString: String) {
        interactor?.downloadAndSaveImage(from: urlString)
    }
}

extension DetailsPresenter: DetailsInteractorOutputProtocol {
    func success(message: String) {
        view?.show(message: message)
    }
    
    func error(message: String) {
        view?.show(message: message)
    }
    
    
}
