//
//  DetailsViewController.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 28/01/25.
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusCoreDesignSystem

class DetailsViewController: UIViewController {
	var presenter: DetailsPresenterProtocol?
    
    /// Views for this controller
    let mainView = DetailsView()

	override func viewDidLoad() {
        super.viewDidLoad()
        view = mainView
        
        setupGestures()
        guard let photo = presenter?.photo else{
            return
        }
        mainView.setup(photo: photo)
        
        
    }
    
    private func setupGestures() {
        mainView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(close)))
        
        mainView.downloadButton.onClick = {
            self.showDSLoader()
            guard let photo = self.presenter?.photo else{
                self.hideDSLoader()
                return
            }
            self.presenter?.downloadAndSaveImage(from:photo.links.download )
        }
    }
    
    @objc func close(){
        dismiss(animated: true)
    }
    
    
}

extension DetailsViewController: DetailsViewProtocol {
    func stopLoader() {
        hideDSLoader()
    }
    
    
    func show(message:String){
        hideDSLoader()
        ZDSSnackBarManager.shared.show(
            style: .gray,
            message: message,
            actionText: "Ver",
            color: .zeusPrimaryColor,
            duration: 5
        ){
            self.presenter?.openGallery()
            
        }
    }
    
}
