//
//  DetailsRouter.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 28/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class DetailsRouter: DetailsWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule(photo:Photo) -> UIViewController {
        let view = DetailsViewController()
        let interactor = DetailsInteractor()
        let router = DetailsRouter()
        let presenter = DetailsPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        presenter.photo = photo
        
        return view
    }
    
    func openGallery() {
        if let url = URL(string: "photos-redirect://") {
            UIApplication.shared.open(url, options: [:], completionHandler: nil)
        }
    }
    
}
