//
//  GalleryView+Layout.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 27/01/25.
//  Template generated by UPAX Zeus
//

import UIKit

extension GalleryView {
    func addViews() {
        self.addSubview(searchBar)
        self.addSubview(collection)
        self.addSubview(paginator)
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            paginator.bottomAnchor.constraint(equalTo: self.safeAreaLayoutGuide.bottomAnchor),
            paginator.leadingAnchor.constraint(equalTo: self.safeAreaLayoutGuide.leadingAnchor,constant: 20),
            paginator.trailingAnchor.constraint(equalTo: self.safeAreaLayoutGuide.trailingAnchor,constant: -20),
            
            collection.bottomAnchor.constraint(equalTo: paginator.topAnchor),
            collection.trailingAnchor.constraint(equalTo: paginator.trailingAnchor,constant: -20 ),
            collection.leadingAnchor.constraint(equalTo: paginator.leadingAnchor, constant: 20),
            collection.topAnchor.constraint(equalTo: searchBar.bottomAnchor),
            
            searchBar.topAnchor.constraint(equalTo: self.safeAreaLayoutGuide.topAnchor),
            searchBar.leadingAnchor.constraint(equalTo: self.safeAreaLayoutGuide.leadingAnchor,constant: 20),
            searchBar.trailingAnchor.constraint(equalTo: self.safeAreaLayoutGuide.trailingAnchor,constant: -20),
            
        ])
    }
}
