//
//  GalleryView.swift
//  zeus-ios-sdk-gallery-tl
//
//  Created DSI Soporte Tecnico on 27/01/25.
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusCoreDesignSystem

class GalleryView: UIView {
    // MARK: Child views
    
    var searchBar: ZDSNavigationSearchBar = {
        let searchBar = ZDSNavigationSearchBar()
        searchBar.translatesAutoresizingMaskIntoConstraints = false
        searchBar.searchTextField.attributedPlaceholder =  NSAttributedString.init(
            string: "Busca una palabra",
            attributes: [NSAttributedString.Key.foregroundColor: UIColor.dark600 ?? .gray]
        )
        searchBar.setBackgroundImage(UIImage(), for: .any, barMetrics: .default)
        searchBar.tintColor = .zeusPrimaryColor
        searchBar.showsCancelButton = true
        searchBar.keyboardType = .alphabet
        return searchBar
    }()
    
    let collection:UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .vertical
        
        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        return collectionView
    }()
    
    let paginator:PaginatorView={
        let view = PaginatorView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    // MARK: Initializers
    init() {
        super.init(frame: .zero)
        backgroundColor = .white
        addViews()
        setupConstraints()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
