//
//  MainViewController.swift
//  zeus-ios-sdk-webviews-manager
//
//  Created DSI Soporte Tecnico on 21/01/25.
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusGalleryTl
import ZeusSessionInfo
import ZeusCoreInterceptor

class MainViewController: UIViewController {
    /// Views for this controller
    let mainView = MainView()

    override func loadView() {
        super.loadView()
        self.view = mainView
        setupGestures()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        registerActions()
    }
    
    func registerActions(){
        GalleryFlow.registerAction()
    }
    
    func setupGestures(){
        mainView.form.stateButton.onClick = {
            SessionInfo.shared.user = User(zeusId: "", employeeNumber: "", name: self.mainView.form.nameTextField.text, lastName: "", secondLastName: "", photo: "", job: "", area: "", mail: "", phoneNumber: "", countryCode: 52, leaderZeusId: "", udnId: 101)
            SessionInfo.shared.company = Company(zeusId: "", companyId: 1, name: "Upax", photo: "", miniature: "", primaryColor: "#e54ee0", secondaryColor: "", titleColor: "", iconColor: "")
            ZCInterceptor.shared.startFlow(forAction: ZCIInternalZeusKeys.livePhotos, navigateDelegate: self)
            
        }
    }
    
    
}

extension MainViewController:ZCInterceptorDelegate{
    func didFailToEnterFlow(error: NSError) {
        debugPrint(error.localizedDescription)
    }
    
    
}

